# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               CUNYSec
tagline:             'Security Community @ CUNY'
description:         'Community Driven Security'
url:                 /
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Nolan Hu
  url:               https://twitter.com/aznspy256
  email:             aznspy256@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/cunysec
twitter:			http://twitter.com/cunysec

# Theme Author
theme:
creator:			Nolan Hu
codename:			CUNYSec
