# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               CUNYsec
tagline:             'Security community @ CUNY'
description:         'Community Driven Security'
url:                 http://cunysec.com
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Nolan Hu
  url:               https://twitter.com/aznspy256
  email:             aznspy256@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/cunysec
twitter:			http://twitter.com/cunysec

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
creator:			Rizky Ariestiyansyah
codename:			Naringu
